gerrit-mysql:
  container_name: gerrit-mysql
  restart: always
  image: mysql:5.6.25
  net: local_network
  volumes:
    - gerrit_mysql_data:/var/lib/mysql
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: gerritpassword
    MYSQL_USER: gerrit
    MYSQL_PASSWORD: gerrit
    MYSQL_DATABASE: gerrit

gerrit:
  container_name: gerrit
  restart: always
  #build: ../images/docker-gerrit/
  image: ranaskr/adop-gerrit:0.1.6
  privileged: true
  net: local_network
  user: root
  volumes:
    - git_repos:/var/git/repos
    - gerrit_review_site:/var/gerrit/review_site
  expose:
    - "8080"
    - "29418"
  environment:
    LDAP_ACCOUNTPATTERN  : "(cn=${username})"
    LDAP_ACCOUNTFULLNAME : "${cn}"
    LDAP_GROUPPATTERN : "(cn=${groupname})"
    LDAP_GROUPMEMBERPATTERN : "(uniqueMember=${dn})"
  environment:
    - "dependency:container==gerrit-mysql"
    - "REPO_PATH=/var/git/repos"
    - "WEBURL=http://localhost/gerrit/"
    - "DATABASE_TYPE=mysql"
    - "DB_HOSTNAME=gerrit-mysql"
    - "DB_PORT=3306"
    - "DB_NAME=gerrit"
    - "DB_USER=gerrit"
    - "DB_PASSWORD=gerrit"
    - "AUTH_LOGOUTURL=http://localhost/gerrit/"
    - "AUTH_TYPE=LDAP"
    - "GERRIT_PASSWORD=43f86fb35c9b4486"
    - "JENKINS_PASSWORD=68b11cffafeb4823"
    - "INITIAL_ADMIN_USER=adop"
    - "INITIAL_ADMIN_PASSWORD=a8001443b3f69930"
    - "LDAP_SERVER=ldap:389"
    - "LDAP_ACCOUNTBASE=dc=ldap,dc=example,dc=com"
    - "LDAP_ACCOUNTEMAILADDRESS=mail"
    - "LDAP_USERNAME=cn=admin,dc=ldap,dc=example,dc=com"
    - "LDAP_PASSWORD=896da35166ec6937"
    - "LDAP_GROUPBASE=ou=groups,dc=ldap,dc=example,dc=com"
    - "HTTPD_LISTENURL=proxy-http://0.0.0.0:8080/gerrit"
    - "USER_NAME=gerrit@adop"
    - "USER_EMAIL=Gerrit Code Review"
    - "DOWNLOAD_SCHEME=http"
