srana-gerrit-mysql:
  container_name: srana-gerrit-mysql
  restart: always
  image: mysql:5.6.25
  net: local_network
  volumes:
    - srana_gerrit_mysql_data:/var/lib/mysql
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: sranagerritpassword
    MYSQL_USER: gerrit
    MYSQL_PASSWORD: gerrit
    MYSQL_DATABASE: gerrit

sranagerrit:
  container_name: sranagerrit
  restart: always
  #build: ../images/docker-gerrit/
  image: ranaskr/adop-gerrit:0.1.4
  privileged: true
  net: local_network
  user: root
  volumes:
    - srana_git_repos:/var/git/repos
    - srana_gerrit_review_site:/var/gerrit/review_site
  expose:
    - "8080"
    - "29418"
  environment:
    LDAP_ACCOUNTPATTERN  : "(cn=${username})"
    LDAP_ACCOUNTFULLNAME : "${cn}"
    LDAP_GROUPPATTERN : "(cn=${groupname})"
    LDAP_GROUPMEMBERPATTERN : "(uniqueMember=${dn})"
  environment:
    - "dependency:container==srana-gerrit-mysql"
    - "REPO_PATH=/var/git/repos"
    - "WEBURL=http://localhost/gerrit/"
    - "DATABASE_TYPE=mysql"
    - "DB_HOSTNAME=srana-gerrit-mysql"
    - "DB_PORT=3306"
    - "DB_NAME=gerrit"
    - "DB_USER=gerrit"
    - "DB_PASSWORD=gerrit"
    - "AUTH_LOGOUTURL=http://localhost/gerrit/"
    - "AUTH_TYPE=LDAP"
    - "GERRIT_PASSWORD=286d6dcc415b3185"
    - "JENKINS_PASSWORD=a42b4f37d4fb6421"
    - "INITIAL_ADMIN_USER=adop"
    - "INITIAL_ADMIN_PASSWORD=0128532a75d17417"
    - "LDAP_SERVER=ldap:389"
    - "LDAP_ACCOUNTBASE=dc=ldap,dc=example,dc=com"
    - "LDAP_ACCOUNTEMAILADDRESS=mail"
    - "LDAP_USERNAME=cn=admin,dc=ldap,dc=example,dc=com"
    - "LDAP_PASSWORD=c10929687b8c3445"
    - "LDAP_GROUPBASE=ou=groups,dc=ldap,dc=example,dc=com"
    - "HTTPD_LISTENURL=proxy-http://0.0.0.0:8080/gerrit"
    - "USER_NAME=gerrit@adop"
    - "USER_EMAIL=Gerrit Code Review"
    - "DOWNLOAD_SCHEME=http"
